### ISSUE TITLE
ToC switches unexpectedly.

### ISSUE THREAD

**Issue by aleksei-korolev** [iota-community/iota-wiki#645] opened 2022-07-19 15:14 UTC
**Is your feature request related to a problem? Please describe.**

When I click on a table of contents entry, my table of contents is sometimes unexpectedly replaced with a different one. For example, [here](http://wiki.iota.org/wallets/what-is-a-wallet) `Developer/IOTA 2.0 DevNet Wallet` leads to an article in the same space, but `Developer/CLI Wallet` leads to a new space, and I have no means to predict it.

**Describe the solution you'd like**

Add an indication if a ToC entry leads to another space.

**Describe alternatives you've considered**

1) Keep everything in the same space.
2) Make an explicit higher-level hierarchy (so in "/wallet/" it would display Wallet (expanded) and CLI Wallet (as a link), and in "/cli-wallet" in would display Wallet (collapsed) and CLI Wallet (as a link).

**Comment by Dr-Electron** [comment] 2022-07-20 19:25
Duplicate of https://github.com/iota-community/iota-wiki/issues/637

**Closed by Dr-Electron** 2022-07-20 19:25 UTC
Labels: duplicate, feature
